---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: linuxptp-daemon
  namespace: openshift-ptp
  annotations:
    target.workload.openshift.io/management: '{"effect":"PreferredDuringScheduling"}'
spec:
  selector:
    matchLabels:
      app: linuxptp-daemon
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: linuxptp-daemon
    spec:
      hostNetwork: true
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - operator: Exists
      serviceAccountName: linuxptp-daemon
      containers:
      - name: linuxptp-daemon-container
        resources:
          limits:
            cpu: 20m
          requests:
            cpu: 20m
            memory: 50Mi
        securityContext:
          privileged: true
        image: quay.io/vgrinber/linuxptp-daemon:2
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "/usr/local/bin/ptp --alsologtostderr" ]
        imagePullPolicy: Always
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: config-volume
          mountPath: /etc/linuxptp
        - mountPath: /host
          name: host
      volumes:
        - name: config-volume
          configMap:
            name: linuxptp-configmap
        - hostPath:
            path: /
            type: Directory
          name: host            
